/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WillBuilderRouteImport } from './routes/will-builder'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FamilyOfficeRouteImport } from './routes/family-office'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalsInsuranceRouteImport } from './routes/portals.insurance'
import { Route as PortalsHouseholdManagersRouteImport } from './routes/portals.household-managers'
import { Route as PortalsFamilyOfficesRouteImport } from './routes/portals.family-offices'
import { Route as PortalsFamiliesRouteImport } from './routes/portals.families'
import { Route as PortalsCpasRouteImport } from './routes/portals.cpas'
import { Route as PortalsAttorneysRouteImport } from './routes/portals.attorneys'
import { Route as PortalsAdvisorsRouteImport } from './routes/portals.advisors'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminPropertyImageTestRouteImport } from './routes/admin.property-image-test'
import { Route as AdminEmailPreviewRouteImport } from './routes/admin.email-preview'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPlaidWebhookRouteImport } from './routes/api/public/plaid-webhook'
import { Route as ApiPublicPlaidRetentionSweepRouteImport } from './routes/api/public/plaid-retention-sweep'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksRevenuecatRouteImport } from './routes/api/public/webhooks/revenuecat'

const WillBuilderRoute = WillBuilderRouteImport.update({
  id: '/will-builder',
  path: '/will-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyOfficeRoute = FamilyOfficeRouteImport.update({
  id: '/family-office',
  path: '/family-office',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsInsuranceRoute = PortalsInsuranceRouteImport.update({
  id: '/portals/insurance',
  path: '/portals/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsHouseholdManagersRoute =
  PortalsHouseholdManagersRouteImport.update({
    id: '/portals/household-managers',
    path: '/portals/household-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalsFamilyOfficesRoute = PortalsFamilyOfficesRouteImport.update({
  id: '/portals/family-offices',
  path: '/portals/family-offices',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsFamiliesRoute = PortalsFamiliesRouteImport.update({
  id: '/portals/families',
  path: '/portals/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsCpasRoute = PortalsCpasRouteImport.update({
  id: '/portals/cpas',
  path: '/portals/cpas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsAttorneysRoute = PortalsAttorneysRouteImport.update({
  id: '/portals/attorneys',
  path: '/portals/attorneys',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsAdvisorsRoute = PortalsAdvisorsRouteImport.update({
  id: '/portals/advisors',
  path: '/portals/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertyImageTestRoute = AdminPropertyImageTestRouteImport.update({
  id: '/property-image-test',
  path: '/property-image-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailPreviewRoute = AdminEmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaidWebhookRoute = ApiPublicPlaidWebhookRouteImport.update({
  id: '/api/public/plaid-webhook',
  path: '/api/public/plaid-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaidRetentionSweepRoute =
  ApiPublicPlaidRetentionSweepRouteImport.update({
    id: '/api/public/plaid-retention-sweep',
    path: '/api/public/plaid-retention-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRevenuecatRoute =
  ApiPublicWebhooksRevenuecatRouteImport.update({
    id: '/api/public/webhooks/revenuecat',
    path: '/api/public/webhooks/revenuecat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficiaries': typeof BeneficiariesRoute
  '/budgets': typeof BudgetsRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/family-office': typeof FamilyOfficeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/household': typeof HouseholdRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/protect': typeof ProtectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/will-builder': typeof WillBuilderRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/email-preview': typeof AdminEmailPreviewRoute
  '/admin/property-image-test': typeof AdminPropertyImageTestRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portals/advisors': typeof PortalsAdvisorsRoute
  '/portals/attorneys': typeof PortalsAttorneysRoute
  '/portals/cpas': typeof PortalsCpasRoute
  '/portals/families': typeof PortalsFamiliesRoute
  '/portals/family-offices': typeof PortalsFamilyOfficesRoute
  '/portals/household-managers': typeof PortalsHouseholdManagersRoute
  '/portals/insurance': typeof PortalsInsuranceRoute
  '/api/public/plaid-retention-sweep': typeof ApiPublicPlaidRetentionSweepRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficiaries': typeof BeneficiariesRoute
  '/budgets': typeof BudgetsRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/family-office': typeof FamilyOfficeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/household': typeof HouseholdRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/protect': typeof ProtectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/will-builder': typeof WillBuilderRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/email-preview': typeof AdminEmailPreviewRoute
  '/admin/property-image-test': typeof AdminPropertyImageTestRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portals/advisors': typeof PortalsAdvisorsRoute
  '/portals/attorneys': typeof PortalsAttorneysRoute
  '/portals/cpas': typeof PortalsCpasRoute
  '/portals/families': typeof PortalsFamiliesRoute
  '/portals/family-offices': typeof PortalsFamilyOfficesRoute
  '/portals/household-managers': typeof PortalsHouseholdManagersRoute
  '/portals/insurance': typeof PortalsInsuranceRoute
  '/api/public/plaid-retention-sweep': typeof ApiPublicPlaidRetentionSweepRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficiaries': typeof BeneficiariesRoute
  '/budgets': typeof BudgetsRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/family-office': typeof FamilyOfficeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/household': typeof HouseholdRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/protect': typeof ProtectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/will-builder': typeof WillBuilderRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/email-preview': typeof AdminEmailPreviewRoute
  '/admin/property-image-test': typeof AdminPropertyImageTestRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portals/advisors': typeof PortalsAdvisorsRoute
  '/portals/attorneys': typeof PortalsAttorneysRoute
  '/portals/cpas': typeof PortalsCpasRoute
  '/portals/families': typeof PortalsFamiliesRoute
  '/portals/family-offices': typeof PortalsFamilyOfficesRoute
  '/portals/household-managers': typeof PortalsHouseholdManagersRoute
  '/portals/insurance': typeof PortalsInsuranceRoute
  '/api/public/plaid-retention-sweep': typeof ApiPublicPlaidRetentionSweepRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficiaries'
    | '/budgets'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/family-office'
    | '/forgot-password'
    | '/household'
    | '/intake'
    | '/launch'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/oauth-callback'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/protect'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/timeline'
    | '/unsubscribe'
    | '/verify-email'
    | '/will-builder'
    | '/admin/chats'
    | '/admin/email-preview'
    | '/admin/property-image-test'
    | '/admin/requests'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/portals/advisors'
    | '/portals/attorneys'
    | '/portals/cpas'
    | '/portals/families'
    | '/portals/family-offices'
    | '/portals/household-managers'
    | '/portals/insurance'
    | '/api/public/plaid-retention-sweep'
    | '/api/public/plaid-webhook'
    | '/lovable/email/suppression'
    | '/api/public/webhooks/revenuecat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/beneficiaries'
    | '/budgets'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/family-office'
    | '/forgot-password'
    | '/household'
    | '/intake'
    | '/launch'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/oauth-callback'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/protect'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/timeline'
    | '/unsubscribe'
    | '/verify-email'
    | '/will-builder'
    | '/admin/chats'
    | '/admin/email-preview'
    | '/admin/property-image-test'
    | '/admin/requests'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/portals/advisors'
    | '/portals/attorneys'
    | '/portals/cpas'
    | '/portals/families'
    | '/portals/family-offices'
    | '/portals/household-managers'
    | '/portals/insurance'
    | '/api/public/plaid-retention-sweep'
    | '/api/public/plaid-webhook'
    | '/lovable/email/suppression'
    | '/api/public/webhooks/revenuecat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficiaries'
    | '/budgets'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/family-office'
    | '/forgot-password'
    | '/household'
    | '/intake'
    | '/launch'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/oauth-callback'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/protect'
    | '/reset-password'
    | '/robots.txt'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/timeline'
    | '/unsubscribe'
    | '/verify-email'
    | '/will-builder'
    | '/admin/chats'
    | '/admin/email-preview'
    | '/admin/property-image-test'
    | '/admin/requests'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/portals/advisors'
    | '/portals/attorneys'
    | '/portals/cpas'
    | '/portals/families'
    | '/portals/family-offices'
    | '/portals/household-managers'
    | '/portals/insurance'
    | '/api/public/plaid-retention-sweep'
    | '/api/public/plaid-webhook'
    | '/lovable/email/suppression'
    | '/api/public/webhooks/revenuecat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiariesRoute: typeof BeneficiariesRoute
  BudgetsRoute: typeof BudgetsRoute
  BusinessRoute: typeof BusinessRoute
  ConnectionsRoute: typeof ConnectionsRoute
  EligibilityRoute: typeof EligibilityRoute
  FamilyRoute: typeof FamilyRoute
  FamilyOfficeRoute: typeof FamilyOfficeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HouseholdRoute: typeof HouseholdRoute
  IntakeRoute: typeof IntakeRoute
  LaunchRoute: typeof LaunchRoute
  LegacyRoute: typeof LegacyRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PortfolioRoute: typeof PortfolioRoute
  PreferencesRoute: typeof PreferencesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProtectRoute: typeof ProtectRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WillBuilderRoute: typeof WillBuilderRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PortalsAdvisorsRoute: typeof PortalsAdvisorsRoute
  PortalsAttorneysRoute: typeof PortalsAttorneysRoute
  PortalsCpasRoute: typeof PortalsCpasRoute
  PortalsFamiliesRoute: typeof PortalsFamiliesRoute
  PortalsFamilyOfficesRoute: typeof PortalsFamilyOfficesRoute
  PortalsHouseholdManagersRoute: typeof PortalsHouseholdManagersRoute
  PortalsInsuranceRoute: typeof PortalsInsuranceRoute
  ApiPublicPlaidRetentionSweepRoute: typeof ApiPublicPlaidRetentionSweepRoute
  ApiPublicPlaidWebhookRoute: typeof ApiPublicPlaidWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicWebhooksRevenuecatRoute: typeof ApiPublicWebhooksRevenuecatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/will-builder': {
      id: '/will-builder'
      path: '/will-builder'
      fullPath: '/will-builder'
      preLoaderRoute: typeof WillBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-office': {
      id: '/family-office'
      path: '/family-office'
      fullPath: '/family-office'
      preLoaderRoute: typeof FamilyOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/insurance': {
      id: '/portals/insurance'
      path: '/portals/insurance'
      fullPath: '/portals/insurance'
      preLoaderRoute: typeof PortalsInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/household-managers': {
      id: '/portals/household-managers'
      path: '/portals/household-managers'
      fullPath: '/portals/household-managers'
      preLoaderRoute: typeof PortalsHouseholdManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/family-offices': {
      id: '/portals/family-offices'
      path: '/portals/family-offices'
      fullPath: '/portals/family-offices'
      preLoaderRoute: typeof PortalsFamilyOfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/families': {
      id: '/portals/families'
      path: '/portals/families'
      fullPath: '/portals/families'
      preLoaderRoute: typeof PortalsFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/cpas': {
      id: '/portals/cpas'
      path: '/portals/cpas'
      fullPath: '/portals/cpas'
      preLoaderRoute: typeof PortalsCpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/attorneys': {
      id: '/portals/attorneys'
      path: '/portals/attorneys'
      fullPath: '/portals/attorneys'
      preLoaderRoute: typeof PortalsAttorneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/advisors': {
      id: '/portals/advisors'
      path: '/portals/advisors'
      fullPath: '/portals/advisors'
      preLoaderRoute: typeof PortalsAdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/property-image-test': {
      id: '/admin/property-image-test'
      path: '/property-image-test'
      fullPath: '/admin/property-image-test'
      preLoaderRoute: typeof AdminPropertyImageTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-preview': {
      id: '/admin/email-preview'
      path: '/email-preview'
      fullPath: '/admin/email-preview'
      preLoaderRoute: typeof AdminEmailPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plaid-webhook': {
      id: '/api/public/plaid-webhook'
      path: '/api/public/plaid-webhook'
      fullPath: '/api/public/plaid-webhook'
      preLoaderRoute: typeof ApiPublicPlaidWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plaid-retention-sweep': {
      id: '/api/public/plaid-retention-sweep'
      path: '/api/public/plaid-retention-sweep'
      fullPath: '/api/public/plaid-retention-sweep'
      preLoaderRoute: typeof ApiPublicPlaidRetentionSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/revenuecat': {
      id: '/api/public/webhooks/revenuecat'
      path: '/api/public/webhooks/revenuecat'
      fullPath: '/api/public/webhooks/revenuecat'
      preLoaderRoute: typeof ApiPublicWebhooksRevenuecatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatsRoute: typeof AdminChatsRoute
  AdminEmailPreviewRoute: typeof AdminEmailPreviewRoute
  AdminPropertyImageTestRoute: typeof AdminPropertyImageTestRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatsRoute: AdminChatsRoute,
  AdminEmailPreviewRoute: AdminEmailPreviewRoute,
  AdminPropertyImageTestRoute: AdminPropertyImageTestRoute,
  AdminRequestsRoute: AdminRequestsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiariesRoute: BeneficiariesRoute,
  BudgetsRoute: BudgetsRoute,
  BusinessRoute: BusinessRoute,
  ConnectionsRoute: ConnectionsRoute,
  EligibilityRoute: EligibilityRoute,
  FamilyRoute: FamilyRoute,
  FamilyOfficeRoute: FamilyOfficeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HouseholdRoute: HouseholdRoute,
  IntakeRoute: IntakeRoute,
  LaunchRoute: LaunchRoute,
  LegacyRoute: LegacyRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PortfolioRoute: PortfolioRoute,
  PreferencesRoute: PreferencesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProtectRoute: ProtectRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WillBuilderRoute: WillBuilderRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PortalsAdvisorsRoute: PortalsAdvisorsRoute,
  PortalsAttorneysRoute: PortalsAttorneysRoute,
  PortalsCpasRoute: PortalsCpasRoute,
  PortalsFamiliesRoute: PortalsFamiliesRoute,
  PortalsFamilyOfficesRoute: PortalsFamilyOfficesRoute,
  PortalsHouseholdManagersRoute: PortalsHouseholdManagersRoute,
  PortalsInsuranceRoute: PortalsInsuranceRoute,
  ApiPublicPlaidRetentionSweepRoute: ApiPublicPlaidRetentionSweepRoute,
  ApiPublicPlaidWebhookRoute: ApiPublicPlaidWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicWebhooksRevenuecatRoute: ApiPublicWebhooksRevenuecatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
