/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/protect': typeof ProtectRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/protect': typeof ProtectRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/business': typeof BusinessRoute
  '/connections': typeof ConnectionsRoute
  '/eligibility': typeof EligibilityRoute
  '/family': typeof FamilyRoute
  '/legacy': typeof LegacyRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/preferences': typeof PreferencesRoute
  '/pricing': typeof PricingRoute
  '/protect': typeof ProtectRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficiaries'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/protect'
    | '/signin'
    | '/signup'
    | '/support'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficiaries'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/protect'
    | '/signin'
    | '/signup'
    | '/support'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/beneficiaries'
    | '/business'
    | '/connections'
    | '/eligibility'
    | '/family'
    | '/legacy'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/preferences'
    | '/pricing'
    | '/protect'
    | '/signin'
    | '/signup'
    | '/support'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  BusinessRoute: typeof BusinessRoute
  ConnectionsRoute: typeof ConnectionsRoute
  EligibilityRoute: typeof EligibilityRoute
  FamilyRoute: typeof FamilyRoute
  LegacyRoute: typeof LegacyRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  PortfolioRoute: typeof PortfolioRoute
  PreferencesRoute: typeof PreferencesRoute
  PricingRoute: typeof PricingRoute
  ProtectRoute: typeof ProtectRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  BusinessRoute: BusinessRoute,
  ConnectionsRoute: ConnectionsRoute,
  EligibilityRoute: EligibilityRoute,
  FamilyRoute: FamilyRoute,
  LegacyRoute: LegacyRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  PortfolioRoute: PortfolioRoute,
  PreferencesRoute: PreferencesRoute,
  PricingRoute: PricingRoute,
  ProtectRoute: ProtectRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
